name = "backend"
compatibility_date = "2024-09-16"


 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYzE3ZTVjOGUtOGZiOS00MzA5LWIwY2ItMmUxMjcwMjI3YWZiIiwidGVuYW50X2lkIjoiMzdjMTI2MDdiM2NmYmEyMjQ1ZTg4MDI5NTlkZDMyODg4MGIwMzdjZTcyZWI0ZmMwNjk0NDU2YmFiZDNmNjhmZCIsImludGVybmFsX3NlY3JldCI6IjNhY2IwYzUyLTdiMDEtNGYxOC1iOWViLThiOWE0NDlmYjE3NyJ9._vhI3_EmOcEbxmQGjIFx7KBdbyVTlE0_0h5kWL4snM4"

SECRET_KEY="mySecretKey"